### ISSUE TITLE
solvespace bindings for python 3.8

### ISSUE THREAD

**Issue by dulouie** [realthunder/slvs_py#1]
Can you please publish the bindings for python 3.8 on pip? 
I tried to install on ubuntu 20.04 with:
`pip3 install py-slvs`

ERROR: Could not find a version that satisfies the requirement py-slvs (from versions: none)
ERROR: No matching distribution found for py-slvs

**Comment by dulouie** [comment]
Or how to i get it running?

**Comment by dulouie** [comment]
Solution is:
1. clone this directory
2. go in the cloned directory
2. `pip install scikit-build`
3. `mkdir py_slvs`
4. `pip install .`

**Comment by RayPS** [comment]
I'm having the same issue.

Python3 -m pip install py_slvs
```
ERROR: Could not find a version that satisfies the requirement py-slvs (from versions: none)
ERROR: No matching distribution found for py-slvs
```

macOS Monterey, Apple Silicon

The method suggested by @dulouie doesn't work for me with build error.

Also one thing I noticed is the ftp server in the build script is no longer available:
https://github.com/realthunder/slvs_py/blob/07243aa944cd2a157fc0238ec1a9ce158902f821/scripts/manylinux.sh#L12
