### ISSUE TITLE
not possible to install on python 3.10

### ISSUE THREAD

**Issue by Sinasta** [realthunder/slvs_py#2]
thank you for your work. I would just like to report that the pip package is not possible to install on python 3.10. If somebody knows i fix i would heavily appreciate.

**Comment by realthunder** [comment]
You're welcome. I'll make a build for 3.10 soon.

**Comment by Sinasta** [comment]
thats great! Thanks alot

**Comment by realthunder** [comment]
FYI, build for Python 3.10 is now avaiable through PyPi.
