### ISSUE TITLE
Tagging all releases

### ISSUE THREAD

**Issue by JulianGmp** [realthunder/slvs_py#8]
Hi there

I just noticed that this package has multiple versions in its [history on pypi](https://pypi.org/project/py-slvs/#history), but only the 1.0.5 release is tagged in [this repo](https://github.com/realthunder/slvs_py/tags).

Can you consider tagging all past and future versions that make it to pypi also on github? It would help users that use a distrubtions package manager over pypi (example: [python-py-slvs  AUR package](https://aur.archlinux.org/packages/python-py-slvs)). Or rather, it would help the maintainers keep track of new versions.

Losely related: hlorus/CAD_Sketcher#395

**Comment by realthunder** [comment]
Sure. It's done.
